С++ try catch. Обработка исключений С++. try catch что это. #120
int main()
{
	setlocale(LC_ALL, "rus");
		string path = "myfil.tt";
		Point point(434, 74, 410);//создаем объект в пространстве
		ofstream fout;//сохраняем данные в файл

	fstream fs;
	ifstream fin;//объект для чтения из файла
 /////////////////////////////////проверка на открытие файла/////////////////////



	fin.exceptions(ifstream::badbit | ifstream::failbit);//чт. включить обработку искл. ситуация, надо напистаь так
	//эт оотносится к ifstream а не к try-catch


	try//здесь что-то пробуем сделать и все гуд, то прога выполняется
		//если исключ-я ситуация, тогда отработает catch
	{
		cout << "Попытка открытия файла!" << endl;
		fin.open(path);//пытаемяс открыть файл//если тут искл-я ситуация, то до нижней строчки мы н едойдем
		//т к сразу в catch
		cout << "Файл успешно открыт!" << endl;
	}
	//catch (const std::exception& ex)//в скобках инфа. которую передали из тела Try.
		//этаинфа м. заворачиваться в различные контейнеры
		//exception-стандартный класс контейнер для заворачивания инфы. ex - это объект данного класса
		//вообще (const std::exception& ex) константная ссылка н аобъект типа exeption, сюда
		//также мы м. поместить др базовый класс исключений вместо exeption
		//который б. содержать методы с большей инфой о ситуации что возникла, например.
		//это возможно т к классы исключ-й связаны цепочкой наследования/Пример- catch (const ifstream::failure& ex)
	//	
	//{
	//	cout << ex.what() << endl;//это метод дл описания что случилось
	//	cout << "Ошибка открытия файла!" << endl;
	//}
catch (const ifstream::failure& ex)
  {
		cout << ex.what() << endl;//это метод дл описания что случилось
		cout<<ex.code() << endl;//инфа о коде ошибки
		cout << "Ошибка открытия файла!" << endl;
	}
//Попытка открытия файла!
//ios_base::failbit set : iostream stream error
//iostream : 1
//Ошибка открытия файла!
	return 0;
}
